### ISSUE TITLE
Config for mirror

### ISSUE THREAD

**Issue by jhult** [j0n17/bitbucket2gitea#1]
Offer config option to enable/disable mirror.

**Comment by j0n17** [comment]
You can now specify the following variables to override the way repositories are migrated to Gitea (defaults to `False` if not specified) :
- `GITEA_MIGRATE_CONFIG_MIRROR`
- `GITEA_MIGRATE_CONFIG_PRIVATE`
- `GITEA_MIGRATE_CONFIG_ISSUES`
- `GITEA_MIGRATE_CONFIG_LABELS`
- `GITEA_MIGRATE_CONFIG_MILESTONES`
- `GITEA_MIGRATE_CONFIG_PULL_REQUESTS`
- `GITEA_MIGRATE_CONFIG_RELEASES`
- `GITEA_MIGRATE_CONFIG_WIKI`

I've updated the README and the code thanks to your input.
